# Generated by Django 2.2 on 2019-04-19 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_rate', models.IntegerField(verbose_name='sending_rate')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scale', max_length=40, verbose_name='scale name')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale', to='scales.Setting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='measurement time')),
                ('weight', models.FloatField(verbose_name='measurement weight')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.Scale')),
            ],
        ),
    ]
